const projects = [
  {title:"VR Corsi Block-Tapping Test",summary:"An immersive implementation of a widely used neuropsychological spatial-memory assessment, developed to examine the feasibility and acceptance of cognitive testing in VR.",role:"Led application design and development; contributed to study design and analysis.",tech:"Unity · C# · VR · usability evaluation",outcome:"Published in Software Impacts (2024); pilot work demonstrated feasibility and user acceptance.",link:"https://doi.org/10.1016/j.simpa.2024.100693"},
  {title:"VR-supported treadmill rehabilitation",summary:"An immersive treadmill training environment designed to support rehabilitation engagement and motor recovery through interactive exercise.",role:"Responsible for VR system design, development, and effectiveness testing.",tech:"Unity · VR · rehabilitation research",outcome:"Published by Springer in Technology for Inclusion and Participation for All (2025).",link:"https://doi.org/10.1007/978-3-032-01628-7_20"},
  {title:"Breathing training in virtual reality",summary:"VR serious-game concepts that teach breathing techniques through dynamically changing environments, explored for post/long-COVID and pulmonary rehabilitation contexts.",role:"Design and research of breathing-focused immersive serious games.",tech:"Unity · VR · biofeedback concepts · serious games",outcome:"Szabó, P., Sik-Lanyi, C. & Cserjési, R. The Impact of Modifying 3D Environments: The Role of Presence in VR Breathing Exercises. Applied Psychophysiology and Biofeedback (2026).",link:"https://doi.org/10.1007/s10484-026-09781-x"},
  {title:"Health education for children with type-1 diabetes",summary:"A user-friendly educational game created to help preschool children learn about type-1 diabetes through age-appropriate interaction.",role:"Designed and developed during MSc studies in Technical Healthcare Applications.",tech:"Android · Java · serious-game design",outcome:"Published in the ICCHP 2024 proceedings; earlier design work presented in 2022.",link:"Patricia_Szabo_List_Of_Publications.pdf"}
];
const publications=[
  {year:"2024",title:"Virtual reality implementation of the Corsi test and pilot study on acceptance",venue:"Software Impacts 21, 100693",note:"Led the VR application’s design and development; contributed to study design and analysis.",url:"https://doi.org/10.1016/j.simpa.2024.100693"},
  {year:"2023",title:"Technologies designed to assist individuals with cognitive impairments",venue:"Sustainability 15, 13490",note:"Main contributor to the conceptual framework and analysis of technology-driven rehabilitation approaches.",url:"https://doi.org/10.3390/su151813490"},
  {year:"2025",title:"A New Path to Recovery: Virtual Reality-Driven Treadmill Exercises",venue:"Springer · Technology for Inclusion and Participation for All",note:"Responsible for system design, VR development, and effectiveness testing.",url:"https://doi.org/10.1007/978-3-032-01628-7_20"},
  {year:"2025",title:"A Full Lifespan Comparison of Virtual Reality Based Cognition Testing",venue:"Springer · Technology for Inclusion and Participation for All",note:"Study of acceptance, effectiveness, and satisfaction across the lifespan.",url:"https://doi.org/10.1007/978-3-032-01628-7_31"}
];
const experience=[
  {date:"2023—present",title:"Researcher & Lecturer",org:"University of Pannonia · 3D Virtual and Digital Environments Research Laboratory",body:"Developing VR and digital-health research; teaching Mobile Programming, Virtual Reality, and Applied Multimedia; supervising BSc and MSc theses."},
  {date:"2023—2025",title:"Researcher",org:"Hungarian Research Network (HUN-REN)",body:"Member of the Cognitive Mapping of Decision Support Systems research group."},
  {date:"2022",title:"Application Engineer",org:"Soloron 40 Zrt. · Budapest",body:"Worked across Docker/Podman containerisation, server management, Azure DevOps release pipelines, Linux administration, project coordination, and customer assistance."},
  {date:"2020—2022",title:"IT Engineer",org:"thyssenkrupp Components Technology Hungary",body:"Software development and testing with PHP, HTML/CSS, and C#; Git/Jira workflows, DevOps and product-owner responsibilities, plugin scripting, service desk, and systems administration."},
  {date:"2017—2019",title:"HR Trainee",org:"Trenkwalder Személyzeti Szolgáltató Kft.",body:"Supported recruitment, contracting, and daily HR operations alongside BSc studies."}
];
document.querySelector('#project-list').innerHTML=projects.map((p,i)=>`<article class="project"><div class="project-index">0${i+1}</div><div><h3>${p.title}</h3><p class="project-summary">${p.summary}</p><div class="project-meta"><div><span>Role</span><p>${p.role}</p></div><div><span>Technology / method</span><p>${p.tech}</p></div></div></div><aside class="project-side"><span>Evidence</span><p>${p.outcome}</p><a href="${p.link}">View related research ↗</a></aside></article>`).join('');
document.querySelector('#publication-list').innerHTML=publications.map(p=>`<article class="publication"><h3><span>${p.year} · ${p.venue}</span>${p.title}<br><a href="${p.url}">DOI / source ↗</a></h3><p>${p.note}</p></article>`).join('');
document.querySelector('#timeline').innerHTML=experience.map(e=>`<article class="timeline-item"><time>${e.date}</time><div><h3>${e.title}</h3><p class="org">${e.org}</p><p>${e.body}</p></div></article>`).join('');
const menu=document.querySelector('.menu-button'),nav=document.querySelector('#nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});nav.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('open')});document.querySelector('#year').textContent=new Date().getFullYear();
